export const PARTICIPANT_CAMERA_STATE_CHANGED = 'PARTICIPANT_CAMERA_STATE_CHANGED'
export const PARTICIPANT_MIC_STATE_CHANGED = 'PARTICIPANT_MIC_STATE_CHANGED'
export const NEW_PARTICIPANTS = 'NEW_PARTICIPANTS'

export const SET_ROOM_OPTIONS = 'SET_ROOM_OPTIONS'

export const IS_DRAWING = 'IS_DRAWING'
export const IS_MOBILE = 'IS_MOBILE'

 